### ISSUE TITLE
AttributeError: module 'time' has no attribute 'clock'

### ISSUE THREAD

**Issue by biazzotto** [joelibaceta/video-to-ascii#30]
I'm trying to run `video-to-ascii` on Python 3.8 and encounter the following error:

```
Traceback (most recent call last):
  File "/home/biazzotto/python/video-to-ascii/.venv/bin/video-to-ascii", line 8, in <module>
    sys.exit(main())
  File "/home/biazzotto/python/video-to-ascii/.venv/lib/python3.8/site-packages/video_to_ascii/cli.py", line 21, in main
    player.play(ARGS.file, strategy=ARGS.strategy, output=ARGS.output, play_audio=ARGS.with_audio)
  File "/home/biazzotto/python/video-to-ascii/.venv/lib/python3.8/site-packages/video_to_ascii/player.py", line 23, in play
    engine.play(output)
  File "/home/biazzotto/python/video-to-ascii/.venv/lib/python3.8/site-packages/video_to_ascii/video_engine.py", line 36, in play
    self.render_strategy.render(self.read_buffer, 
  File "/home/biazzotto/python/video-to-ascii/.venv/lib/python3.8/site-packages/video_to_ascii/render_strategy/ascii_strategy.py", line 120, in render
    t0 = time.clock()
AttributeError: module 'time' has no attribute 'clock'
```

Python version: 3.8.2 (from Ubuntu 20.04 LTS)
video-to-ascii version: 1.2.8

This is caused by removing `time.clock()` function in Python 3.8, as warned [here](https://docs.python.org/3.7/library/time.html#time.clock): `Deprecated since version 3.3, will be removed in version 3.8: The behaviour of this function depends on the platform: use perf_counter() or process_time() instead, depending on your requirements, to have a well defined behaviour.`.

**Comment by TrizlyBear** [comment]
Basically replace `time.clock()` with `time.process_time()` right now, until the owner updates it. (Can make a PR tho)

**Comment by joelibaceta** [comment]
@TrizlyBear  thanks for your advice, change made in https://github.com/joelibaceta/video-to-ascii/commit/81e34317eed5d5830a801718853ae00a6656e052
