### ISSUE TITLE
ZeroDivisionError: float division by zero

### ISSUE THREAD

**Issue by liping17** [joelibaceta/video-to-ascii#34]
root@mail:/disk1# video-to-ascii -f wild.mp4
Traceback (most recent call last):
  File "/usr/local/bin/video-to-ascii", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/video_to_ascii/cli.py", line 21, in main
    player.play(ARGS.file, strategy=ARGS.strategy, output=ARGS.output, play_audio=ARGS.with_audio)
  File "/usr/local/lib/python3.6/dist-packages/video_to_ascii/player.py", line 23, in play
    engine.play(output)
  File "/usr/local/lib/python3.6/dist-packages/video_to_ascii/video_engine.py", line 38, in play
    with_audio=self.with_audio)
  File "/usr/local/lib/python3.6/dist-packages/video_to_ascii/render_strategy/ascii_strategy.py", line 113, in render
    time_delta = 1./fps
ZeroDivisionError: float division by zero

**Comment by MyCatCondo** [comment]
I'm having the same issue, any fix?

**Comment by MyCatCondo** [comment]
#28
