### ISSUE TITLE
ModuleNotFoundError: No module named 'cv2'

### ISSUE THREAD

**Issue by creativegamer03** [joelibaceta/video-to-ascii#36]
`Traceback (most recent call last):
  File "c:\users\carl-\appdata\local\programs\python\python38-32\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\carl-\appdata\local\programs\python\python38-32\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\carl-\AppData\Local\Programs\Python\Python38-32\Scripts\video-to-ascii.exe\__main__.py", line 4, in <module>
  File "c:\users\carl-\appdata\local\programs\python\python38-32\lib\site-packages\video_to_ascii\cli.py", line 3, in <module>
    from . import player
  File "c:\users\carl-\appdata\local\programs\python\python38-32\lib\site-packages\video_to_ascii\player.py", line 4, in <module>
    from . import video_engine as ve
  File "c:\users\carl-\appdata\local\programs\python\python38-32\lib\site-packages\video_to_ascii\video_engine.py", line 3, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'`

Windows 10 32bit
Python 3.8

**Comment by mrinmaydhar** [comment]
just use the following command if you are using anaconda:

`pip install opencv-python`

[Source](https://stackoverflow.com/a/41895783/5726675)
