### ISSUE TITLE
Not Installable

### ISSUE THREAD

**Issue by MyCatCondo** [joelibaceta/video-to-ascii#44]
`pip3 install ./video-to-ascii
Processing ./video-to-ascii
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-irufanr_/setup.py", line 17, in <module>
        install_package('opencv-python')
      File "/tmp/pip-req-build-irufanr_/setup.py", line 10, in install_package
        main.main(['install', package])
    AttributeError: 'function' object has no attribute 'main'`
I get the same thing using `pip3 install video-to-ascii`
I think there is an error in the code.

**Comment by MyCatCondo** [comment]
I found the issue at `main.main(['install', package])`
Possible fix by removing `main.` and making it `main(['install', package])`. Testing it now.

**Comment by MyCatCondo** [comment]
If this works I will make a PR.

**Comment by aertist** [comment]
> If this works I will make a PR.

any update?

**Comment by MyCatCondo** [comment]
I honestly forgot lol, I gotta retry it if that’s ok

**Comment by joelibaceta** [comment]
Solved in https://github.com/joelibaceta/video-to-ascii/commit/884feea180469e8b59dbde2eed1b64b6920cc8db

**Comment by aertist** [comment]
Now its giving me this error when i execute the `>video-to-ascii -f out.mp4`

`'stty' is not recognized as an internal or external command,
operable program or batch file.
Traceback (most recent call last):
  File "C:\Users\SPECTRE\AppData\Local\Programs\Python\Python37\Scripts\video-to-ascii-script.py", line 33, in <module>
    sys.exit(load_entry_point('video-to-ascii==1.2.6', 'console_scripts', 'video-to-ascii')())
  File "C:\Users\SPECTRE\AppData\Local\Programs\Python\Python37\lib\site-packages\video_to_ascii-1.2.6-py3.7.egg\video_to_ascii\cli.py", line 21, in main
  File "C:\Users\SPECTRE\AppData\Local\Programs\Python\Python37\lib\site-packages\video_to_ascii-1.2.6-py3.7.egg\video_to_ascii\player.py", line 23, in play
  File "C:\Users\SPECTRE\AppData\Local\Programs\Python\Python37\lib\site-packages\video_to_ascii-1.2.6-py3.7.egg\video_to_ascii\video_engine.py", line 38, in play
  File "C:\Users\SPECTRE\AppData\Local\Programs\Python\Python37\lib\site-packages\video_to_ascii-1.2.6-py3.7.egg\video_to_ascii\render_strategy\ascii_strategy.py", line 119, in render
ValueError: not enough values to unpack (expected 2, got 0)`

**Comment by joelibaceta** [comment]
I see. Apparently, you are using it in windows. There are some incompatibilities due to this package use the command "stty size" to obtain the terminal size, which does not seem to be available in windows.

**Comment by xwmx** [comment]
@joelibaceta I'm running into installation errors that might be related to this. The system is macOS 10.15.7 with homebrew-installed `pip 21.1.3 from /usr/local/lib/python3.9/site-packages/pip (python 3.9)`. It looks like installation encounters `AttributeError: module 'pip.__main__' has no attribute '_main'` errors with version 1.3.0 and 1.2.9, then succeeds with 1.2.8:

```bash
❯ pip3 install video-to-ascii --no-cache
Collecting video-to-ascii
  Downloading video_to_ascii-1.3.0.tar.gz (6.9 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/local/opt/python@3.9/bin/python3.9 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/dq/y_2c6lt546z2mwnfc7l8ng7r0000gn/T/pip-install-a8_ieo08/video-to-ascii_d21ad87acf6e4b60a0fb8b9a84b7183a/setup.py'"'"'; __file__='"'"'/private/var/folders/dq/y_2c6lt546z2mwnfc7l8ng7r0000gn/T/pip-install-a8_ieo08/video-to-ascii_d21ad87acf6e4b60a0fb8b9a84b7183a/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/dq/y_2c6lt546z2mwnfc7l8ng7r0000gn/T/pip-pip-egg-info-967vtpra
         cwd: /private/var/folders/dq/y_2c6lt546z2mwnfc7l8ng7r0000gn/T/pip-install-a8_ieo08/video-to-ascii_d21ad87acf6e4b60a0fb8b9a84b7183a/
    Complete output (14 lines):
    Traceback (most recent call last):
      File "/private/var/folders/dq/y_2c6lt546z2mwnfc7l8ng7r0000gn/T/pip-install-a8_ieo08/video-to-ascii_d21ad87acf6e4b60a0fb8b9a84b7183a/setup.py", line 11, in install_package
        main.main(['install', package])
    AttributeError: 'function' object has no attribute 'main'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/dq/y_2c6lt546z2mwnfc7l8ng7r0000gn/T/pip-install-a8_ieo08/video-to-ascii_d21ad87acf6e4b60a0fb8b9a84b7183a/setup.py", line 21, in <module>
        install_package('opencv-python')
      File "/private/var/folders/dq/y_2c6lt546z2mwnfc7l8ng7r0000gn/T/pip-install-a8_ieo08/video-to-ascii_d21ad87acf6e4b60a0fb8b9a84b7183a/setup.py", line 14, in install_package
        __main__._main(['install', package])
    AttributeError: module 'pip.__main__' has no attribute '_main'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/42/36/b3ba2181793646f6c32234527ab51e74905a10139273a1056cf717367504/video_to_ascii-1.3.0.tar.gz#sha256=acd6186e13dd17f5c75aa0f254917eeeae609c7680997778840929c7b26cd584 (from https://pypi.org/simple/video-to-ascii/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Downloading video_to_ascii-1.2.9.tar.gz (6.1 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/local/opt/python@3.9/bin/python3.9 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/dq/y_2c6lt546z2mwnfc7l8ng7r0000gn/T/pip-install-a8_ieo08/video-to-ascii_96c93360054a4829a0343f402029af25/setup.py'"'"'; __file__='"'"'/private/var/folders/dq/y_2c6lt546z2mwnfc7l8ng7r0000gn/T/pip-install-a8_ieo08/video-to-ascii_96c93360054a4829a0343f402029af25/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/dq/y_2c6lt546z2mwnfc7l8ng7r0000gn/T/pip-pip-egg-info-q9tx5x32
         cwd: /private/var/folders/dq/y_2c6lt546z2mwnfc7l8ng7r0000gn/T/pip-install-a8_ieo08/video-to-ascii_96c93360054a4829a0343f402029af25/
    Complete output (14 lines):
    Traceback (most recent call last):
      File "/private/var/folders/dq/y_2c6lt546z2mwnfc7l8ng7r0000gn/T/pip-install-a8_ieo08/video-to-ascii_96c93360054a4829a0343f402029af25/setup.py", line 11, in install_package
        main.main(['install', package])
    AttributeError: 'function' object has no attribute 'main'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/dq/y_2c6lt546z2mwnfc7l8ng7r0000gn/T/pip-install-a8_ieo08/video-to-ascii_96c93360054a4829a0343f402029af25/setup.py", line 21, in <module>
        install_package('opencv-python')
      File "/private/var/folders/dq/y_2c6lt546z2mwnfc7l8ng7r0000gn/T/pip-install-a8_ieo08/video-to-ascii_96c93360054a4829a0343f402029af25/setup.py", line 14, in install_package
        __main__._main(['install', package])
    AttributeError: module 'pip.__main__' has no attribute '_main'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/5a/f2/2022fcbc812b7eb46ea4fb43e1f67359d05b7719fa4099000ce83e9a85da/video_to_ascii-1.2.9.tar.gz#sha256=09bc0e8d26eaa24a2d92c667e690b59feda4bb6c44c0b10c71b61e490be8dabd (from https://pypi.org/simple/video-to-ascii/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Downloading video_to_ascii-1.2.8-py3-none-any.whl (10 kB)
Requirement already satisfied: ffmpeg-python in /usr/local/lib/python3.9/site-packages (from video-to-ascii) (0.2.0)
Requirement already satisfied: xtermcolor in /usr/local/lib/python3.9/site-packages (from video-to-ascii) (1.3)
Requirement already satisfied: future in /usr/local/lib/python3.9/site-packages (from ffmpeg-python->video-to-ascii) (0.18.2)
Installing collected packages: video-to-ascii
Successfully installed video-to-ascii-1.2.8
```

Then when trying to view a video with version 1.2.8, the following error is displayed:

```
Traceback (most recent call last):
  File "/usr/local/bin/video-to-ascii", line 5, in <module>
    from video_to_ascii.cli import main
  File "/usr/local/lib/python3.9/site-packages/video_to_ascii/cli.py", line 3, in <module>
    from . import player
  File "/usr/local/lib/python3.9/site-packages/video_to_ascii/player.py", line 4, in <module>
    from . import video_engine as ve
  File "/usr/local/lib/python3.9/site-packages/video_to_ascii/video_engine.py", line 3, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'
```

**Comment by joelibaceta** [comment]
@xwmx, you don't have OpenCV installed. It is a required dependency
