### ISSUE TITLE
echo -en '[2J'

### ISSUE THREAD

**Issue by pog222** [joelibaceta/video-to-ascii#50]
When I try to run the command (video-to-ascii -f video.mp4) it just responds with
`echo -en '[2J'
echo -en '[2J'`
It doesn't play the video and just says that.

**Comment by pog222** [comment]
I am using windows command terminal by the way

**Comment by Modus0** [comment]
Im having this issue too :/

**Comment by Modus0** [comment]
> I am using windows command terminal by the way

so i figured out that you have to change the directory from where you're runing this from using the change directory command to the path where you are keeping the video file however now im encountering this :/ : 

echo -en '←[2J'
'stty' is not recognized as an internal or external command,
operable program or batch file.
Traceback (most recent call last):
  File "C:\Users\0lympus\AppData\Local\Programs\Python\Python39\Scripts\video-to-ascii-script.py", line 33, in <module>
    sys.exit(load_entry_point('video-to-ascii==1.2.9', 'console_scripts', 'video-to-ascii')())
  File "c:\users\0lympus\appdata\local\programs\python\python39\lib\site-packages\video_to_ascii\cli.py", line 21, in main
    player.play(ARGS.file, strategy=ARGS.strategy, output=ARGS.output, play_audio=ARGS.with_audio)
  File "c:\users\0lympus\appdata\local\programs\python\python39\lib\site-packages\video_to_ascii\player.py", line 23, in play
    engine.play(output)
  File "c:\users\0lympus\appdata\local\programs\python\python39\lib\site-packages\video_to_ascii\video_engine.py", line 36, in play
    self.render_strategy.render(self.read_buffer,
  File "c:\users\0lympus\appdata\local\programs\python\python39\lib\site-packages\video_to_ascii\render_strategy\ascii_strategy.py", line 120, in render
    rows, cols = os.popen('stty size', 'r').read().split()
ValueError: not enough values to unpack (expected 2, got 0)

**Comment by Modus0** [comment]
> I am using windows command terminal by the way

Hey Bro, since no one else decided to help let me step in here, I decided to get the ubuntu VM and was able to make it work a little better still with some issues. Im having trouble resizing the video but id suggest you try it through ubuntu linux since it aint workin in windows
