### ISSUE TITLE
AttributeError: module 'time' has no attribute 'clock'

### ISSUE THREAD

**Issue by WolfGames** [joelibaceta/video-to-ascii#59]
**Describe the bug**

**To Reproduce**
1. Go to terminal
2. type video-to-ascii -f myvideo.mp4
3. See error

**Expected behavior**
When i run command in terminal it displays:
```
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2544.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2544.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\CripoGames\PycharmProjects\badApple\venv\Scripts\video-to-ascii.exe\__main__.py", line 7, in <module>
  File "c:\users\cripogames\pycharmprojects\badapple\venv\lib\site-packages\video_to_ascii\cli.py", line 21, in main
    player.play(ARGS.file, strategy=ARGS.strategy, output=ARGS.output, play_audio=ARGS.with_audio)
  File "c:\users\cripogames\pycharmprojects\badapple\venv\lib\site-packages\video_to_ascii\player.py", line 23, in play
    engine.play(output)
  File "c:\users\cripogames\pycharmprojects\badapple\venv\lib\site-packages\video_to_ascii\video_engine.py", line 36, in play
    self.render_strategy.render(self.read_buffer,
  File "c:\users\cripogames\pycharmprojects\badapple\venv\lib\site-packages\video_to_ascii\render_strategy\ascii_strategy.py", line 120, in render
    t0 = time.clock()
AttributeError: module 'time' has no attribute 'clock'
```

I have all needed modules installed

**Screenshots**
![Screenshot](https://user-images.githubusercontent.com/58263600/116698289-7ebe0a80-a9c4-11eb-9be3-7dd757f3477e.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Uhhh i'm running this on PyCharm not browser

**Smartphone (please complete the following information):**
 - Version 1.2.9

**Comment by RajvirSingh1313** [comment]
I am getting it too, I hope they will fix it as soon as possible.

**Comment by FrankRx41** [comment]
+1
My py version is 3.9.5

**Comment by ziposcar** [comment]
+1
3.9.2

**Comment by yusufusta** [comment]
#43 it's merged. just need the new version of package

**Comment by RajvirSingh1313** [comment]
Thanks Alot, gona make some cool projects with it

**Comment by Indhar01** [comment]
**upgrade your sqlalchemy**
`pip install sqlalchemy --upgrade`

**Comment by waipeinan** [comment]
same error, AttributeError: module 'time' has no attribute 'clock'

have upgraded sqlalchemy, 
changes all instance of clock replacing with time (three or four instances I think)

**Comment by scillidan** [comment]
+1
3.10.2

**Comment by RedDragonTix** [comment]
same here on 3.10

**Comment by Traiver** [comment]
I think the solution will also work for Windows, so here is the solution for Unix:

folder: cd /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/video_to_ascii/render_strategy
edit the following file: ascii_strategy.py

add the following line after "import time": time.clock = time.time

This should solve the problem for playing the video.

**Comment by zachmx** [comment]
> I think the solution will also work for Windows, so here is the solution for Unix:
> 
> folder: cd /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/video_to_ascii/render_strategy edit the following file: ascii_strategy.py
> 
> add the following line after "import time": time.clock = time.time
> 
> This should solve the problem for playing the video.

This fixed the problem for my system.  running on linux (pop os).

the directory for that file in my system was located at 
~/.local/lib/python3.10/site-packages/video_to_ascii/render_strategy
