### ISSUE TITLE
ModuleNotFoundError: No module named 'image_processor'

### ISSUE THREAD

**Issue by joelibaceta** [joelibaceta/video-to-ascii#6]
In some installations, the user gets an error message when try to run the command video-to-ascii

```
Traceback (most recent call last):
  File "/usr/local/bin/video-to-ascii", line 4, in <module>
    import video_to_ascii
  File "/usr/local/lib/python3.7/site-packages/video_to_ascii/__init__.py", line 4, in <module>
    from image_processor import processor
ModuleNotFoundError: No module named 'image_processor'
```

**Comment by joelibaceta** [comment]
Solved in https://github.com/joelibaceta/video-to-ascii/commit/dc816a7664f84730f93782c3950f3cb51b5532cd
