### ISSUE TITLE
Installation failed on Ubuntu 18.04.5

### ISSUE THREAD

**Issue by vincentkollebolle** [joelibaceta/video-to-ascii#61]
Hi ! In love of your work I would like to use it ! 
I tried to install it but fail with this error that I don't get : 
`pip3 install video-to-ascii --install-option="--with-audio"
/usr/lib/python3/dist-packages/pip/commands/install.py:212: UserWarning: Disabling all use of wheels due to the use of --build-options / --global-options / --install-options.
  cmdoptions.check_install_build_global(options)
Collecting video-to-ascii
  Using cached https://files.pythonhosted.org/packages/42/36/b3ba2181793646f6c32234527ab51e74905a10139273a1056cf717367504/video_to_ascii-1.3.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-fp1jbfaw/video-to-ascii/setup.py", line 21, in <module>
        install_package('opencv-python')
      File "/tmp/pip-build-fp1jbfaw/video-to-ascii/setup.py", line 10, in install_package
        from pip._internal import main
    ModuleNotFoundError: No module named 'pip._internal'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-fp1jbfaw/video-to-ascii`

**Comment by joelibaceta** [comment]
https://github.com/joelibaceta/video-to-ascii/blob/master/setup.py#L10 this should solve it

**Comment by vincentkollebolle** [comment]
Certainly ! 
I need to try this. I guess I need to git clone the project and try a manual installation ?  
What about the pip3 ? 

Anyway, I try it and tell you if everything is ok asap ! 
Thanks a lot for the quick answer !

**Comment by joelibaceta** [comment]
@vincentkollebolle It seems that this change should already be in pipy and available in the installation through pip3. It would be great if you tell us a bit more about your  environment in order to validate if there is an additional case to consider concerning dependencies incompatibility
