### ISSUE TITLE
Audio not working

### ISSUE THREAD

**Issue by RedDragonTix** [joelibaceta/video-to-ascii#76]
I get the following error:

Traceback (most recent call last):
  File "/home/tavi/.local/bin/video-to-ascii", line 33, in <module>
    sys.exit(load_entry_point('video-to-ascii==1.3.0', 'console_scripts', 'video-to-ascii')())
  File "/home/tavi/.local/lib/python3.10/site-packages/video_to_ascii/cli.py", line 21, in main
    player.play(ARGS.file, strategy=ARGS.strategy, output=ARGS.output, play_audio=ARGS.with_audio)
  File "/home/tavi/.local/lib/python3.10/site-packages/video_to_ascii/player.py", line 23, in play
    engine.play(output)
  File "/home/tavi/.local/lib/python3.10/site-packages/video_to_ascii/video_engine.py", line 36, in play
    self.render_strategy.render(self.read_buffer, 
  File "/home/tavi/.local/lib/python3.10/site-packages/video_to_ascii/render_strategy/ascii_strategy.py", line 126, in render
    stream.write(data)
  File "/usr/lib/python3.10/site-packages/pyaudio.py", line 585, in write
    pa.write_stream(self._stream, frames, num_frames,
SystemError: PY_SSIZE_T_CLEAN macro must be defined for '#' formats

**Comment by michael555444** [comment]
same bug error s happened

**Comment by daudix-UFO** [comment]
same

**Comment by RadinhoDePilha** [comment]
This is a little incompatibility of Pyaudio ( and some others modules ) with python 3.10 that aren't resolved at now. In your cases, just executing in python 3.9 or earlier will resolve imediatly.
