### ISSUE TITLE
Crash on Python3.8+ due to time.clock() in render_strategy/ascii_strategy.py

### ISSUE THREAD

**Issue by jinmu333** [joelibaceta/video-to-ascii#77]
**Describe the bug**
Crash on Python3.8+ due to time.clock() in render_strategy/ascii_strategy.py

on Python3.8+  `time.clock()` should be replaced by`time.perf_counter()`

**To Reproduce**
1. install python3.9.9
2. install video-to-ascii
3. run video-to-ascii
4. and you will get an error bellow

```bash
Traceback (most recent call last):
  File "/Users/hanfuliu/Downloads/AE/./venv/bin/video-to-ascii", line 8, in <module>
    sys.exit(main())
  File "/Users/hanfuliu/Downloads/AE/venv/lib/python3.9/site-packages/video_to_ascii/cli.py", line 21, in main
    player.play(ARGS.file, strategy=ARGS.strategy, output=ARGS.output, play_audio=ARGS.with_audio)
  File "/Users/hanfuliu/Downloads/AE/venv/lib/python3.9/site-packages/video_to_ascii/player.py", line 23, in play
    engine.play(output)
  File "/Users/hanfuliu/Downloads/AE/venv/lib/python3.9/site-packages/video_to_ascii/video_engine.py", line 36, in play
    self.render_strategy.render(self.read_buffer, 
  File "/Users/hanfuliu/Downloads/AE/venv/lib/python3.9/site-packages/video_to_ascii/render_strategy/ascii_strategy.py", line 120, in render
    t0 = time.clock()
AttributeError: module 'time' has no attribute 'clock'
```

**Expected behavior**
Hope support python3.9.9

**Desktop (please complete the following information):**
 - OS: [Macos]
 - Version [12.1]

**Comment by Solider1337** [comment]
same problem /windows 11, python 3.9

**Comment by theamircodex** [comment]
same problem win 10 python 3.8

**Comment by joelibaceta** [comment]
Yup, I'm still dealing with windows compatibility

**Comment by steb-git** [comment]
same problem here, but i was using Ubuntu 22.04 LTS when that happened :shrug:
