### ISSUE TITLE
Error on windows 10 

### ISSUE THREAD

**Issue by WhiteTrashAndy** [joelibaceta/video-to-ascii#91]
First i couldn't install the latest verison 1.2.9 had kept getting an error with the setup.py file looked like this =
 python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [15 lines of output]
      Traceback (most recent call last):
        File "C:\Users\E6420\AppData\Local\Temp\pip-install-3_kvnnuu\video-to-ascii_7c27b79175614cdfbf33f1272e424542\setup.py", line 11, in install_package
          main.main(['install', package])
      AttributeError: 'function' object has no attribute 'main'
      During handling of the above exception, another exception occurred:
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\E6420\AppData\Local\Temp\pip-install-3_kvnnuu\video-to-ascii_7c27b79175614cdfbf33f1272e424542\setup.py", line 21, in <module>
          install_package('opencv-python')
        File "C:\Users\E6420\AppData\Local\Temp\pip-install-3_kvnnuu\video-to-ascii_7c27b79175614cdfbf33f1272e424542\setup.py", line 14, in install_package
          __main__._main(['install', package])
      AttributeError: module 'pip.__main__' has no attribute '_main 

rectified with this=
"`pip3 install -U video-to-ascii==1.2.8 --install-option="-with-audio"` "
used the "--install option" because a simple "-with--audio" didnt work. 

**So far so good, right?**

_Here is where i am having trouble_

i try to use it with this `video-to-ascii -f ava.mp4` and it produces error code=
"'video-to-ascii' is not recognized as an internal or external command,
operable program or batch file." 

What am i doing wrong, i mean did it not install? if i try to check using 
`video-to-ascii --version` 
it produces the same error code=
"'video-to-ascii' is not recognized as an internal or external command,
operable program or batch file." 
and I'm an idiot really i dont know of another way to verify a correct install, and I tried 
`start video-to-ascii.......` [used "......." for simplicity] it says that there is no file path for that... please help me

**Comment by Asilver-jpg** [comment]
Bump. Same error on WSL Ubuntu.

**Comment by xybytz** [comment]
Same error on Ventura.
