### ISSUE TITLE
Cannot install on MacOSx Ventura

### ISSUE THREAD

**Issue by mcjka** [joelibaceta/video-to-ascii#94]
**Describe the bug**
Installation giving metadata generation error
**To Reproduce**
1. Go to terminal
2. pip3 install video-to-ascii

**Expected behavior**

**Screenshots**
https://imgur.com/a/ndQ33Rl
**Desktop (please complete the following information):**
 - OS: MacOs
 - Browser: safari
 - Version: Ventura

**Additional context**
This is the error:

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [15 lines of output]
      Traceback (most recent call last):
        File "/private/var/folders/86/yx40vcz53rg___l6zql2k7kr0000gq/T/pip-install-qkvdcde7/video-to-ascii_78c06d8d68e248f3a87895e1ab035cd3/setup.py", line 11, in install_package
          main.main(['install', package])
      AttributeError: 'function' object has no attribute 'main'
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/86/yx40vcz53rg___l6zql2k7kr0000gq/T/pip-install-qkvdcde7/video-to-ascii_78c06d8d68e248f3a87895e1ab035cd3/setup.py", line 21, in <module>
          install_package('opencv-python')
        File "/private/var/folders/86/yx40vcz53rg___l6zql2k7kr0000gq/T/pip-install-qkvdcde7/video-to-ascii_78c06d8d68e248f3a87895e1ab035cd3/setup.py", line 14, in install_package
          __main__._main(['install', package])
      AttributeError: module 'pip.__main__' has no attribute '_main'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by pbx** [comment]
Yup. Seeing that here too. Looks like the code depends on some pip internals that have changed.

Looks like the code hasn't been substantially touched in about 5 years. I imagine if you made a venv based on five-years-ago Python, and installed five-years-ago pip, installing this app (into that venv) might work. 

On the other hand, that might just peel back the

**Comment by xybytz** [comment]
Do you know how many times across Ubuntu, Mac and Windows I have encountered that issue on any module!? Way too many. Luckily, i believe this could be a fix: https://github.com/pypa/pip/issues/5240
